version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 homie.wsgi:application
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      # Montar la carpeta media dinámicamente si los usuarios suben avatares (importante en prod)
      - ./media:/app/media
      # Mantener persistencia base de datos SQLite por demo (suele usarse BD en servicio aparte para Prod)
      - ./db.sqlite3:/app/db.sqlite3
