"""
Django settings for Homie project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Cargar variables de entorno desde el archivo .env
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-3-+xl8j=_3b%&xs0&!)(uug0a)%w&bf3(zyj^z1*9nx64l6aoe')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '*').split(',')


# Application definition

CLOUDINARY_URL = os.environ.get('CLOUDINARY_URL', '')
_CLOUD_NAME = os.environ.get('CLOUDINARY_CLOUD_NAME', '')
_API_KEY     = os.environ.get('CLOUDINARY_API_KEY', '')
_API_SECRET  = os.environ.get('CLOUDINARY_API_SECRET', '')

# Si hay variables separadas, úsalas (más fiable que parsear la URL)
if _CLOUD_NAME and _API_KEY and _API_SECRET:
    CLOUDINARY_STORAGE = {
        'CLOUD_NAME': _CLOUD_NAME,
        'API_KEY': _API_KEY,
        'API_SECRET': _API_SECRET,
    }
    INSTALLED_APPS = [
        'django.contrib.admin',
        'django.contrib.auth',
        'django.contrib.contenttypes',
        'django.contrib.sessions',
        'django.contrib.messages',
        'django.contrib.staticfiles',
        'cloudinary_storage',
        'cloudinary',
        'accounts',
        'houses',
        'housetasks',
        'housebedrooms',
        'chats',
        'shopping',
        'widget_tweaks',
    ]
    STORAGES = {
        "default": {"BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage"},
        "staticfiles": {"BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"},
    }
    print(f"[HOMIE] ✅ Cloudinary activo: cloud={_CLOUD_NAME}")
elif CLOUDINARY_URL:
    # Fallback: parsear la URL combinada
    import re as _re
    _m = _re.match(r'cloudinary://([^:]+):([^@]+)@(.+)', CLOUDINARY_URL.strip())
    if _m:
        CLOUDINARY_STORAGE = {
            'CLOUD_NAME': _m.group(3).strip(),
            'API_KEY': _m.group(1).strip(),
            'API_SECRET': _m.group(2).strip(),
        }
        INSTALLED_APPS = [
            'django.contrib.admin',
            'django.contrib.auth',
            'django.contrib.contenttypes',
            'django.contrib.sessions',
            'django.contrib.messages',
            'django.contrib.staticfiles',
            'cloudinary_storage',
            'cloudinary',
            'accounts',
            'houses',
            'housetasks',
            'housebedrooms',
            'chats',
            'shopping',
            'widget_tweaks',
        ]
        STORAGES = {
            "default": {"BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage"},
            "staticfiles": {"BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"},
        }
        print(f"[HOMIE] ✅ Cloudinary activo via URL: cloud={_m.group(3).strip()}")
    else:
        print(f"[HOMIE] ❌ CLOUDINARY_URL mal formateada: '{CLOUDINARY_URL[:30]}...'")
        INSTALLED_APPS = [
            'django.contrib.admin',
            'django.contrib.auth',
            'django.contrib.contenttypes',
            'django.contrib.sessions',
            'django.contrib.messages',
            'django.contrib.staticfiles',
            'accounts',
            'houses',
            'housetasks',
            'housebedrooms',
            'chats',
            'shopping',
            'widget_tweaks',
        ]
else:
    print("[HOMIE] ⚠️  Cloudinary NO configurado - imágenes en disco local")
    INSTALLED_APPS = [
        'django.contrib.admin',
        'django.contrib.auth',
        'django.contrib.contenttypes',
        'django.contrib.sessions',
        'django.contrib.messages',
        'django.contrib.staticfiles',
        'accounts',
        'houses',
        'housetasks',
        'housebedrooms',
        'chats',
        'shopping',
        'widget_tweaks',
    ]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

AUTHENTICATION_BACKENDS = [
    'accounts.backends.EmailOrUsernameModelBackend',
    'django.contrib.auth.backends.ModelBackend',
]

ROOT_URLCONF = 'homie.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'homie.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASE_URL = os.environ.get('DATABASE_URL', '')

if DATABASE_URL:
    import re as _re2
    _db = _re2.match(r'postgresql://([^:]+):([^@]+)@([^/]+)/(.+)', DATABASE_URL)
    if _db:
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': _db.group(4),
                'USER': _db.group(1),
                'PASSWORD': _db.group(2),
                'HOST': _db.group(3).split(':')[0],
                'PORT': _db.group(3).split(':')[1] if ':' in _db.group(3) else '5432',
            }
        }
    else:
        DATABASES = {'default': {'ENGINE': 'django.db.backends.sqlite3', 'NAME': BASE_DIR / 'db.sqlite3'}}
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'Europe/Madrid'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Media files (User uploaded images, etc.)
# Si CLOUDINARY_URL está configurada, se usa Cloudinary (ver INSTALLED_APPS arriba)
# Si no, guardar en disco (desarrollo local)
if not CLOUDINARY_URL:
    MEDIA_URL = '/media/'
    MEDIA_ROOT = BASE_DIR / 'media'
else:
    MEDIA_URL = '/media/'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'accounts.CustomUser'

LOGIN_URL = 'login'   
LOGIN_REDIRECT_URL = 'inicio'  
LOGOUT_REDIRECT_URL = 'index'

# Email Config - Automático
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')       # Email visible del remitente
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')  # Clave SMTP
BREVO_SMTP_LOGIN = os.environ.get('BREVO_SMTP_LOGIN', '')      # Login interno de Brevo (ab3bed001@smtp-brevo.com)

if EMAIL_HOST_USER:
    # Brevo SMTP - puerto 2525 con TLS (bypass del bloqueo de render)
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = 'smtp-relay.brevo.com'
    EMAIL_PORT = 2525
    EMAIL_USE_TLS = True
    EMAIL_USE_SSL = False
    EMAIL_TIMEOUT = 10  # timeout de 10 segundos para no bloquear gunicorn
    # Brevo usa un login SMTP interno diferente al email del remitente
    if BREVO_SMTP_LOGIN:
        EMAIL_HOST_USER = BREVO_SMTP_LOGIN
else:
    # Simular envíos en la terminal para desarrollo local
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

DEFAULT_FROM_EMAIL = os.environ.get('EMAIL_HOST_USER', 'noreply@homie.local')