# Generated by Django 6.0.2 on 2026-03-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='deletion_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
