# Generated by Django 6.0.2 on 2026-04-14 22:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0004_housenote_personaldiaryentry_reminder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='is_read',
        ),
        migrations.AddField(
            model_name='reminder',
            name='read_by',
            field=models.ManyToManyField(blank=True, related_name='read_reminders', to=settings.AUTH_USER_MODEL),
        ),
    ]
