# Generated by Django 6.0.2 on 2026-04-15 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0007_chatroom_created_at_chatroom_creator_chatroom_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='gifs_unlocked',
            field=models.BooleanField(default=False),
        ),
    ]
