# Generated by Django 6.0.2 on 2026-04-16 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0008_house_gifs_unlocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='spent_points',
            field=models.IntegerField(default=0),
        ),
    ]
