# Generated by Django 6.0.2 on 2026-05-07 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0009_house_spent_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
