# Generated by Django 6.0.2 on 2026-05-07 20:38

from django.db import migrations, models
from django.utils.text import slugify

def populate_slugs(apps, schema_editor):
    House = apps.get_model('houses', 'House')
    for house in House.objects.filter(slug__isnull=True) | House.objects.filter(slug=""):
        base_slug = slugify(house.name) if house.name else 'casa'
        if not base_slug:
            base_slug = 'casa'
        slug = base_slug
        counter = 1
        while House.objects.filter(slug=slug).exclude(id=house.id).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1
        house.slug = slug
        # We cannot call custom methods on the Model instance loaded from migrations, 
        # so just simple save without calling overrides is supported via historical model.
        house.save()


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0010_house_slug'),
    ]

    operations = [
        migrations.RunPython(populate_slugs, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='house',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
