# Generated by Django 6.0.2 on 2026-05-08 01:37

from django.db import migrations, models
from django.utils.text import slugify

def populate_group_slugs(apps, schema_editor):
    ChatRoom = apps.get_model('houses', 'ChatRoom')
    for room in ChatRoom.objects.filter(is_group=True):
        if not room.slug:
            base_slug = slugify(room.name) if room.name else 'grupo'
            if not base_slug:
                base_slug = 'grupo'
            slug = base_slug
            counter = 1
            while ChatRoom.objects.filter(slug=slug, house=room.house_id).exclude(id=room.id).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            room.slug = slug
            room.save()

class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0011_alter_house_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True),
        ),
        migrations.RunPython(populate_group_slugs, reverse_code=migrations.RunPython.noop),
    ]
