# Generated by Django 6.0.2 on 2026-04-16 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housetasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='has_been_completed',
            field=models.BooleanField(default=False),
        ),
    ]
