# Generated by Django 6.0.2 on 2026-04-14 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housebedrooms', '0002_privatenickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseprofile',
            name='completed_shopping_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='houseprofile',
            name='completed_tasks_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
