# Generated by Django 6.0.2 on 2026-04-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housebedrooms', '0003_houseprofile_completed_shopping_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseprofile',
            name='bedroom_poster',
            field=models.CharField(default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='houseprofile',
            name='bedroom_rug_style',
            field=models.CharField(default='rug_default', max_length=30),
        ),
        migrations.AddField(
            model_name='houseprofile',
            name='bedroom_wallcolor',
            field=models.CharField(default='#d6c3a3', max_length=20),
        ),
        migrations.AddField(
            model_name='houseprofile',
            name='unlock_poster_gaming',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='houseprofile',
            name='unlock_stars_rug',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='houseprofile',
            name='unlock_wallcolor',
            field=models.BooleanField(default=False),
        ),
    ]
