# Generated by Django 6.0.2 on 2026-02-13 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='points',
        ),
        migrations.AddField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(default='2000-01-01', max_length=150),
            preserve_default=False,
        ),
    ]
