# Generated by Django 6.0.2 on 2026-04-15 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gifs_unlocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='wallet_balance',
            field=models.IntegerField(default=0),
        ),
    ]
