# Generated by Django 6.0.2 on 2026-04-16 02:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_gifs_unlocked_customuser_wallet_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='equipped_frame',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='UserFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_name', models.CharField(max_length=100)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'frame_name')},
            },
        ),
    ]
