# Generated by Django 6.0.2 on 2026-05-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingitem',
            name='quantity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
